#!/usr/bin/env bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Only makes sense for the top level to define CWD
if [ "$1" != "buildDep" ] && [ "$CWD" ]; then
  cwd="$( cd "$CWD" && pwd )"
else
  cwd="$(pwd)"
fi

duploGlobal="$dir/../lib/node_modules/duplo"
if [ -d "$duploGlobal" ]; then
  duplo="$( cd $duploGlobal && pwd )"
else
  duplo="$( cd "$dir/.." && pwd )"
fi

json="$duplo/node_modules/.bin/JSON.sh"
gulp="$duplo/node_modules/.bin/gulp"
gulpfile="$duplo/cli/gulpfile.js"
run="$gulp --base $duplo --gulpfile $gulpfile"
version=`cat "$duplo/package.json" | $json | egrep '\["version"\]' | egrep -o '[0-9\.]+'`

abort() {
  printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
}

showVersion() {
  echo 'Duplo v'$version
}

case "$1" in
  version|ver|-v|--ver|--version)
    showVersion
    ;;
  
  new)
    name=$2
    repo=$3

    if [ -z "$name" ]; then
      abort "There must be a name."
    fi
    if [ -z "$repo" ]; then
      abort "There must be a Git repo URL."
    fi

    # Make sure it's a Git repo
    git init
    # Main modules directory structure
    mkdir -p "$cwd/app/modules"
    # Asset directory
    mkdir -p "$cwd/app/assets"
    # Stylus directory
    mkdir -p "$cwd/app/styl"
    # Dev directory
    mkdir -p "$cwd/dev"
    # Component.IO
    echo '{"name":"'$name'","version":"0.0.0"}' > "$cwd/component.json"
    # We need a README
    echo "# $name" > "README.md"
    # Ignore files
    cat <<- EOF >> "$cwd/.gitignore"
public/
components/
tmp/
EOF
    # Initial commit
    git add .
    git commit -m "Initialized with duplo"
    # We need a develop branch
    git checkout -b develop
    # We need to set the repo
    git remote add origin $3
    # Confirm
    echo "Initialized with duplo"
    ;;

  dev)
    if [ -z "$NODE_ENV" ]; then
      NODE_ENV="dev"
    fi
    form="$2"

    if [ -z "$2" ]; then
      CWD=$cwd NODE_ENV=$NODE_ENV BUILD_MODE=dev $run dev
    else
      CWD=$cwd NODE_ENV=$NODE_ENV BUILD_MODE=dev $run dev:$2
    fi
    ;;
  
  build)
    if [ -z "$NODE_ENV" ]; then
      NODE_ENV="prod"
    fi

    if [ -z "$2" ]; then
      CWD=$cwd NODE_ENV=$NODE_ENV BUILD_MODE=prod $run build
    else
      CWD=$cwd NODE_ENV=$NODE_ENV BUILD_MODE=prod $run build:$2
    fi
    ;;

  buildDep|builddep)
    if [ -z "$2" ]; then
      abort "dependency name required"
    else
      CWD=$cwd NODE_ENV=$NODE_ENV BUILD_MODE=prod $run build:$2
    fi
    ;;

  patch)
    CWD=$cwd $run release:patch
    ;;

  minor)
    CWD=$cwd $run release:minor
    ;;

  major)
    CWD=$cwd $run release:major
    ;;

  *)
    abort "Unknown command"

esac
