#!/usr/bin/env bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
modules="$dir/../lib/node_modules"
duplo="$modules/duplo"
grunt="$modules/grunt-cli/bin/grunt"
gruntfile="$duplo/cli/Gruntfile.coffee"
run="$grunt --base $duplo --gruntfile $gruntfile"

case "$1" in
  dev)
    NODE_ENV=dev $run dev
    ;;

  build)
    NODE_ENV=prod $run build
    echo $run
    ;;

  patch)
    $run release:patch
    ;;

  minor)
    $run release:minor
    ;;

  major)
    $run release:major
    ;;

  *)
esac
