#!/usr/bin/env bash

if [ "$2" ]; then
  cwd=$2
else
  cwd="$(pwd)"
fi

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
modules="$dir/../lib/node_modules"
duplo="$modules/duplo"
grunt="$modules/grunt-cli/bin/grunt"
gruntfile="$duplo/cli/Gruntfile.coffee"
run="$grunt --base $duplo --gruntfile $gruntfile"

case "$1" in
  dev)
    if [ -z "$NODE_ENV" ]; then
      NODE_ENV="dev"
    fi

    CWD=$cwd NODE_ENV=$NODE_ENV $run dev
    ;;

  build)
    if [ -z "$NODE_ENV" ]; then
      NODE_ENV="prod"
    fi

    CWD=$cwd NODE_ENV=$NODE_ENV $run build
    ;;

  patch)
    CWD=$cwd $run release:patch
    ;;

  minor)
    CWD=$cwd $run release:minor
    ;;

  major)
    CWD=$cwd $run release:major
    ;;

  *)
esac
